numpy is a python library
it is used for working with arrays
it is short for numerical python
it is used for computation and processing of single and multidimensional array of elements
smaller memory consumption and better runtime behavior

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]
arr=np.array(l)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
type(l)

list

In [7]:
ar=np.array([[1,2,4],[4,5,6]])
ar

array([[1, 2, 4],
       [4, 5, 6]])

In [8]:
ar.ndim

2

In [9]:
arr[2]

np.int64(3)

In [10]:
dd=np.array([[[[1,2],[2,3]]]])
dd.ndim

4

In [11]:
dd[0][0][0][1]

np.int64(2)

In [12]:
ff=np.array([1,2,3,4],dtype='float64')

In [13]:
print(ff)

[1. 2. 3. 4.]


In [14]:
dd.shape

(1, 1, 2, 2)

In [15]:
pp=np.array([[1,2,3,4],[3,4,5,6]])
pp[0,2]=200
print(pp)

[[  1   2 200   4]
 [  3   4   5   6]]


In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
type(np.zeros((2,3)))

numpy.ndarray

In [18]:
a=np.zeros((2,3))

In [19]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('float64')

In [22]:
one=np.ones((2,3),dtype='int32')

In [23]:
print(one)

[[1 1 1]
 [1 1 1]]


In [24]:
b=np.full((2,3),30,dtype='float')

In [25]:
print(b)

[[30. 30. 30.]
 [30. 30. 30.]]


In [26]:
np.random.rand(2,3)

array([[0.20996487, 0.16378146, 0.25428018],
       [0.04679921, 0.48724003, 0.1661192 ]])

In [28]:
w=np.array([1,2,3,4])
h=np.array([20,30,40,40])
bmi=w/(h)**2
print(bmi)

[0.0025     0.00222222 0.001875   0.0025    ]


In [29]:
a=[1,2,3]
b=[44,5,5]
w=np.array(a)
h=np.array(b)
bmi=w/(h)**2

In [30]:
print(bmi)

[0.00051653 0.08       0.12      ]
